### ISSUE TITLE
Backward Compatability Issue between Python 3.11 and PyQt5

### ISSUE THREAD

**Issue by TH1622EE** [RadarBook/software#10]
I recently purchased this AMAZING book and ran through the installation procedures of the repository on my Windows 11 machine with Python 3.11. 6 and Anaconda Command Client version 1.11.3 installed, and there is an issue with the backward compatibility with PyQt5. When run from Git-Bash after verifying **ALL** required packages are installed, to include succesfully installing the *pyradar* package as described in the text, I get the following error:

```text
Traceback (most recent call last):
  File "<my-path-to-repo>/pyradar/Chapter01/RadarBook.py", line 13, in <module>
    from Chapter01.ui.RadarBook_ui import Ui_MainWindow
ModuleNotFoundError: No module named 'Chapter01'
```

I was able to resolve the issue by creating a new Python environment using Python 3.6.4 and installing the required packages as follows:

`conda create --name radarbookenv python=3.6.4`
`conda activate radarbookenv`
`pip install numpy scipy matplotlib pyqt5`
`pip install -e ~/<my-path-to-Chapter01>/RadarBook.py`
`cd <my-path-to-pyradar/Chapter01>`
`python ./RadarBook.py`

The GUI works great and everything functions as expected now, but I've yet to run through many of the chapters and examples. In the meantime I will attempt to integrate comparable and compatible versions of required packages for backward compatibility in my fork, and if successful I'll clone the repo, integrate and commit my changes, and submit a pull request.

**Thank you Andy for creating this tool!**

**Comment by RadarBook** [comment]
Thanks for the kind comments!  That's very interesting, I've had a couple of other compatibility issues.  Looking forward to see your pull request!

**Comment by HandsomeLee-9966** [comment]
The dataset corresponding to your book on the website“ https://www.sdms.afrl.af.mil "Unable to access. However, the dataset is very important, otherwise we won't be able to perform some simulations under the guidance of the book. Are there any suggestions to obtain the corrspondding dataset? 
      Looking forward to your reply , thank you very much!

**Comment by RadarBook** [comment]
Which dataset are you referring to?
