### ISSUE TITLE
The explanation of the python code needed

### ISSUE THREAD

**Issue by yt7589** [RadarBook/software#12]
It is a great book to learn radar technology. But I found a problem. The formula used in python code is different from the formula in the theory part. I know that we should do some simplification when implement the algorithm. It is very difficult for me a radar new comer to follow up. I don't know which formula to use the theory one or the one used in the code. Why not just use the theory formula to calculate? It would be better to provide the reason why use the simplified formula in python code instead of the theory one. Where can I find this kind of information?

**Comment by RadarBook** [comment]
If you can tell me which equation you are referring to, I can provide a detailed answer.  Thanks!
