### ISSUE TITLE
LFM Pulse Ambiguity

### ISSUE THREAD

**Issue by smithry67** [RadarBook/software#5]
Hey,

I believe there is an issue with the LFM pulse ambiguity function. I have edited the bandwidth term in lfm_pulse_ambiguity_example.m to be related to a desired resolution and converted the zero doppler cut figure's time axis to meters and I do not get the resolution. I have attached the edited example file along with a potential fix for the ambiguity function. 
[mFiles.zip](https://github.com/RadarBook/software/files/8238038/mFiles.zip)

-Ryan

**Comment by RadarBook** [comment]
Good catch Ryan!  Thank you for pointing this out.  The error was in line 16 of lfm_pulse.m and also occurred in ambiguity_function.py line 65.  The multiplication by pi was the error.  It should simply be removed.  I corrected this in both places and committed the updated functions.  Thank you again, it makes the code base better.
