### ISSUE TITLE
Missing mat files in SDMS

### ISSUE THREAD

**Issue by sebaheredia** [RadarBook/software#9]
Hi,

Thank you for this repository.
I was trying to run the back projection algorithm, but on the https://www.sdms.afrl.af.mil/index.php website, there are no MAT files available. I only found HDF5 files. Could you help me with this issue?

Thanks in advance.

**Comment by TH1622EE** [comment]
[This link](https://www.mathworks.com/matlabcentral/answers/341722-how-to-convert-hdf5-format-to-mat-data#:~:text=answer%20this%20question.-,Accepted%20Answer,-Jan%20%20%20on%2024) should work for you to manually convert the HDF5 files to MAT files in MATLAB.

**Comment by RadarBook** [comment]
Thanks Tim!
